name: yt_creator_boost
description: "A Flutter app for YouTube creators to discover and grow their channels"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  # Google Sign In
  google_sign_in: ^7.2.0

  # UI Utils
  flutter_screenutil: ^5.9.3

  # State Management
  flutter_bloc: ^9.1.1

  # Routing
  go_router: ^16.2.1

  # Dependency Injection
  get_it: ^8.2.0

  # Network & Data
  dio: ^5.4.3+1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.3

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/