name: yt_creator_boost
description: "A Flutter app for YouTube creators to discover and grow their channels"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4

  # State Management (Clean Architecture)
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Form Validation
  formz: ^0.6.1

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Google Services
  google_sign_in: ^6.2.1

  # AdMob
  google_mobile_ads: ^4.0.0

  # Network & Data
  http: ^1.1.0
  dio: ^5.4.0
  json_annotation: ^4.8.1

  # UI & Utils
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  # Development
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

    ###  assets:
    ###    - assets/images/
    ###    - assets/icons/
  ###   - assets/animations/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf